services:
  # PostgreSQL для Django
  db:
    image: postgres:15
    container_name: django-db
    environment:
      POSTGRES_DB: aikademiya
      POSTGRES_USER: aikademiya
      POSTGRES_PASSWORD: aikademiya
    ports:
      - "5432:5432"
    volumes:
      - aikademiya_pgdata:/var/lib/postgresql/data
    networks:
      - default

  # Django API-only приложение
  web:
    build: .
    container_name: aikademiya-backend
    command: python aikademiya/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: aikademiya
      POSTGRES_USER: aikademiya
      POSTGRES_PASSWORD: aikademiya
      POSTGRES_HOST: db
      TEMPORAL_ADDRESS: temporal:7233
      DJANGO_DEBUG: "True"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default
      - temporal-network

  # Vue.js фронтенд (полностью независимый)
  frontend:
    build:
      context: ./frontend
    container_name: aikademiya-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000/api
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - web
    networks:
      - default

  # PostgreSQL для Temporal
  postgresql:
    image: postgres:12
    container_name: temporal-postgres
    environment:
      POSTGRES_DB: temporal
      POSTGRES_USER: temporal
      POSTGRES_PASSWORD: temporal
    volumes:
      - temporal_pgdata:/var/lib/postgresql/data
    networks:
      - temporal-network

  # Temporal server
  temporal:
    image: temporalio/auto-setup:1.27.2
    container_name: temporal
    environment:
      DB: postgres12
      DB_PORT: 5432
      POSTGRES_USER: temporal
      POSTGRES_PWD: temporal
      POSTGRES_SEEDS: postgresql
    depends_on:
      - postgresql
    ports:
      - "7233:7233"
    networks:
      - temporal-network

  # Temporal CLI
  temporal-admin-tools:
    image: temporalio/admin-tools:1.27
    container_name: temporal-admin-tools
    environment:
      TEMPORAL_CLI_ADDRESS: temporal:7233
    depends_on:
      - temporal
    networks:
      - temporal-network

  # Temporal UI
  temporal-ui:
    image: temporalio/ui:2.37.2
    container_name: temporal-ui
    ports:
      - "8080:8080"
    environment:
      TEMPORAL_ADDRESS: temporal:7233
      TEMPORAL_CORS_ORIGINS: http://localhost:8080
    depends_on:
      - temporal
    networks:
      - temporal-network

volumes:
  aikademiya_pgdata:
  temporal_pgdata:

networks:
  temporal-network:
    driver: bridge