version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: aikademiya
      POSTGRES_USER: aikademiya
      POSTGRES_PASSWORD: aikademiya
    ports:
      - "5432:5432"
  web:
    build: .
    command: python aikademiya/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: aikademiya
      POSTGRES_USER: aikademiya
      POSTGRES_PASSWORD: aikademiya
      POSTGRES_HOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
  n8n:
    image: n8nio/n8n:1
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=UTC
