# Generated by Django 5.2.4 on 2025-07-21 18:34

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.UserManager()),
            ],
        ),
    ]