# Generated by Django 5.2.4 on 2025-07-22 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="course",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
        migrations.AddField(
            model_name="course",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="difficulty",
            field=models.CharField(
                choices=[
                    ("beginner", "beginner"),
                    ("intermediate", "intermediate"),
                    ("advanced", "advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="initiated_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_courses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="normalized_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="course",
            name="original_topic",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "draft"),
                    ("pending_confirmation", "pending_confirmation"),
                    ("confirmed", "confirmed"),
                    ("rejected", "rejected"),
                    ("in_progress", "in_progress"),
                    ("completed", "completed"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="writing_style",
            field=models.CharField(
                choices=[
                    ("formal", "formal"),
                    ("casual", "casual"),
                    ("academic", "academic"),
                    ("practical", "practical"),
                ],
                default="practical",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.category",
            ),
        ),
        migrations.CreateModel(
            name="CourseValidationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("validation_type", models.CharField(max_length=50)),
                ("request_data", models.JSONField()),
                ("response_data", models.JSONField()),
                ("is_successful", models.BooleanField()),
                ("error_message", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
